### ISSUE TITLE
Plans to upgrade to Elm 0.19?

### ISSUE THREAD

**Issue by klazuka** [avh4/elm-fifo#5]
Do you plan to upgrade this package for Elm 0.19? I ask because this project is a dependency of [elm-community/graph](https://github.com/elm-community/graph), which I'd like to upgrade to 0.19. Would it be helpful if I created a PR? I realize that you're well-suited to run `elm-upgrade`, but asking just in case 😄

**Comment by avh4** [comment]
I started https://github.com/avh4/elm-fifo/pull/6, but sadly CI cannot pass yet.  I published beta-1.0.4 from the WIP.

**Comment by avh4** [comment]
Published https://package.elm-lang.org/packages/avh4/elm-fifo/1.0.4/
